### ISSUE TITLE
Shrinking nullable columns

### ISSUE THREAD

**Issue by rubenhelsloot** [lycantropos/hypothesis_sqlalchemy#20]
According to [the hypothesis docs](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.one_of), `st.one_of` shrinks towards elements earlies in the list. For nullable columns, you use `result |= st.none()`, which results in `st.one_of(<other strategy>, st.none())`.

Would it be desirable to interchange the order so the strategy will shrink towards NULLS rather than filled values?

**Comment by lycantropos** [comment]
Sounds reasonable and should be easy to fix.
