### ISSUE TITLE
Support `sqlalchemy` 2

### ISSUE THREAD

**Issue by dycw** [lycantropos/hypothesis_sqlalchemy#38]
Hi, this is a great project. `sqlalchemy` 2 has been released, and it would be great if this supported it.

I'd be happy to open a PR.

**Comment by lycantropos** [comment]
@dycw thanks, I'd be happy to review it!

**Comment by dycw** [comment]
@lycantropos Please find PR https://github.com/lycantropos/hypothesis_sqlalchemy/pull/39.

**Comment by lycantropos** [comment]
Available since [v1.1.0](https://pypi.org/project/hypothesis-sqlalchemy/1.1.0).
