### ISSUE TITLE
Add `Framework :: Hypothesis` PyPI trove classifier

### ISSUE THREAD

**Issue by Zac-HD** [lycantropos/hypothesis_sqlalchemy#4]
The Python Packaging Authority has recently created a new trove classifier to help users find Hypothesis-related packages, as described and demonstrated in HypothesisWorks/hypothesis#1663.

It would be great if this package used it too!

**Comment by lycantropos** [comment]
@Zac-HD: Sure, thanks, I'll do it asap.

**Comment by Zac-HD** [comment]
Awesome!  You might even beat Hypothesis itself to be the first, since we have the whole 'second person reviews' thing :stuck_out_tongue_winking_eye:

**Comment by lycantropos** [comment]
@Zac-HD: done

https://github.com/lycantropos/hypothesis_sqlalchemy/blob/0936376e6e425c4cd3cc3cc28b47644547e7af7a/setup.py#L33
