### ISSUE TITLE
Python 3.7 Crash on import

### ISSUE THREAD

**Issue by dave-brennan** [lycantropos/hypothesis_sqlalchemy#7]
Using with Python 3.7 results in crash on import.

Sample code:

> from hypothesis import strategies
> from hypothesis_sqlalchemy import tables

Stack trace:

> Traceback (most recent call last):
>   File "example_failure.py", line 6, in <module>
>     from hypothesis_sqlalchemy import tables
>   File "/usr/local/lib/python3.7/site-packages/hypothesis_sqlalchemy/tables/__init__.py", line 2, in <module>
>     from .tables import factory
>   File "/usr/local/lib/python3.7/site-packages/hypothesis_sqlalchemy/tables/tables.py", line 7, in <module>
>     from hypothesis_sqlalchemy import columns
>   File "/usr/local/lib/python3.7/site-packages/hypothesis_sqlalchemy/columns.py", line 104, in <module>
>     def non_all_unique_lists_factory(lists: Strategy = lists_factory()
>   File "/usr/local/lib/python3.7/site-packages/hypothesis_sqlalchemy/columns.py", line 87, in lists_factory
>     max_size=max_size)
> TypeError: lists() got an unexpected keyword argument 'average_size'

**Comment by lycantropos** [comment]
It looks like you are using `hypothesis` with version `>=4.0.0`.

From [changelog](https://hypothesis.readthedocs.io/en/latest/changes.html#strategies):
> The `average_size` argument was a no-op and has been removed.
